article.view:
  url: '/article/{id}'
  class: '\Nick\Article\Pages\View'
  parameters:
    - id: 1

article.edit:
  url: '/article/{id}/edit'
  class: '\Nick\Article\Pages\Edit'
  parameters:
    - id: 1

article.delete:
  url: '/article/{id}/delete'
  class: '\Nick\Article\Pages\Delete'
  parameters:
    - id: 1

article.overview:
  url: '/articles'
  class: '\Nick\Article\Pages\Overview'