-
    name: Article
    type: matter
-
    name: Breadcrumb
    type: extension
-
    name: Cache
    type: core
-
    name: Config
    type: core
-
    name: Database
    type: core
-
    name: Entity
    type: core
-
    name: Event
    type: extension
-
    name: ExtensionManager
    type: core
-
    name: File
    type: core
-
    name: Form
    type: core
-
    name: Language
    type: core
-
    name: Manifest
    type: core
-
    name: Menu
    type: matter
-
    name: Page
    type: core
-
    name: Person
    type: core
-
    name: Translation
    type: core
