-
    name: Cache
    type: core
-
    name: Database
    type: core
-
    name: Events
    type: core
-
    name: ExtensionManager
    type: core
-
    name: File
    type: core
-
    name: Form
    type: core
-
    name: Language
    type: core
-
    name: Manifest
    type: core
-
    name: Matter
    type: core
-
    name: Page
    type: core
-
    name: Person
    type: core
-
    name: Translation
    type: core
